context:
  version: "5_1_0"

package:
  name: groovy
  version: ${{ version }}

source:
  url: https://github.com/apache/groovy/archive//GROOVY_${{ version | replace(".", "_") }}.tar.gz
  sha256: 74e324b0f73f151459b6db94baa7ece23ae584e2e76c5567593a89d537cedfc1

build:
  number: 0
  noarch: generic

requirements:
  build:
    - graphviz
    - findutils
    - maven
    - openjdk >=17,<18
    - unzip
    - sed
  run:
    - openjdk

tests:
  - script:
      - groovysh --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - target/generated-resources/licenses/
  summary: Java-based scripting language
  homepage: https://www.groovy-lang.org
  repository: https://github.com/apache/groovy

extra:
  recipe-maintainers:
    - danielnachun
